switches:
  gateway:
    rate-limiting:
      enabled: false
      limit: 100000
      duration-in-seconds: 3600
  security:
    authentication:
      jwt:
        base64-secret: YWRhOTExMzE3ZmJmMWQwODVkMGIzMzc0ZGIxMzVlMDk2Njc3NDZhZmFhNDcwODQ2MDZiYzBiOGIzYzAzYjM2NjU5NTE4MDVkYmVjNDE3NGEyZjVjNjQ4ZmM1ZDBhOTA5NjVjZTliNDU5ZDkwZDMzN2UxMmNkZjI1YmNiZTJiYjk=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000