server:
  port: 8082
dubbo:
  scan:
    base-packages: io.luxyva.switches.connect.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: switch-base
  consumer:
    check: false

management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata
spring:
  profiles:
    active: dev